# Generated by Django 5.2.5 on 2025-08-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctioncategories_auctionlistings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='image_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
