# Generated by Django 5.2.5 on 2025-08-29 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionCategories',
            new_name='AuctionCategorie',
        ),
        migrations.RenameModel(
            old_name='AuctionListings',
            new_name='AuctionListing',
        ),
    ]
